// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XRayJournal.Core;

#nullable disable

namespace XRayJournal.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260902120119_AddPasswordHashAndPwDate")]
    partial class AddPasswordHashAndPwDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CabinetDTOUserDTO", b =>
                {
                    b.Property<int>("CabinetsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersID")
                        .HasColumnType("integer");

                    b.HasKey("CabinetsId", "UsersID");

                    b.HasIndex("UsersID");

                    b.ToTable("CabinetsUsers", (string)null);
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.CabinetDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CabNum")
                        .HasColumnType("text");

                    b.Property<string>("CabinetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Clinic")
                        .HasColumnType("text");

                    b.Property<int?>("IdClinic")
                        .HasColumnType("integer");

                    b.Property<string>("Modality")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdClinic");

                    b.ToTable("Cabinets");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.DepartmentDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.HospitalDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clinic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.NumberDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyNum")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("XRayDate")
                        .HasColumnType("date");

                    b.Property<int>("YearlyNum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.PatientDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MedNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThirdName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.RecordDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("ExamId")
                        .HasColumnType("integer");

                    b.Property<int>("NumberId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("NumberId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.UserDTO", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<int?>("CabinetId")
                        .HasColumnType("integer");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FIOshort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<DateTime>("PwDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PwHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.XRayExamDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Area")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Contrast")
                        .HasColumnType("boolean");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Doctor")
                        .HasColumnType("text");

                    b.Property<int?>("IdCabinet")
                        .HasColumnType("integer");

                    b.Property<bool?>("InOperation")
                        .HasColumnType("boolean");

                    b.Property<string>("Laborant")
                        .HasColumnType("text");

                    b.Property<string>("Side")
                        .HasColumnType("text");

                    b.Property<int?>("XRayCost")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("XRayDate")
                        .HasColumnType("date");

                    b.Property<string>("XRayDiagnose")
                        .HasColumnType("text");

                    b.Property<float>("XRayDose")
                        .HasColumnType("real");

                    b.Property<string>("XRayModality")
                        .HasColumnType("text");

                    b.Property<string>("XRayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("XRayPatology")
                        .HasColumnType("boolean");

                    b.Property<int>("XRayShots")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IdCabinet");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("CabinetDTOUserDTO", b =>
                {
                    b.HasOne("XRayJournal.Core.DTOs.CabinetDTO", null)
                        .WithMany()
                        .HasForeignKey("CabinetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XRayJournal.Core.DTOs.UserDTO", null)
                        .WithMany()
                        .HasForeignKey("UsersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.CabinetDTO", b =>
                {
                    b.HasOne("XRayJournal.Core.DTOs.HospitalDTO", "Hospital")
                        .WithMany("Cabinets")
                        .HasForeignKey("IdClinic");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.DepartmentDTO", b =>
                {
                    b.HasOne("XRayJournal.Core.DTOs.HospitalDTO", "Hospital")
                        .WithMany("Departments")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.RecordDTO", b =>
                {
                    b.HasOne("XRayJournal.Core.DTOs.XRayExamDTO", "Exam")
                        .WithMany("Records")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("XRayJournal.Core.DTOs.NumberDTO", "Number")
                        .WithMany("Records")
                        .HasForeignKey("NumberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("XRayJournal.Core.DTOs.PatientDTO", "Patient")
                        .WithMany("Records")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("XRayJournal.Core.DTOs.UserDTO", "User")
                        .WithMany("Records")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Number");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.XRayExamDTO", b =>
                {
                    b.HasOne("XRayJournal.Core.DTOs.DepartmentDTO", "Department")
                        .WithMany("Exams")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("XRayJournal.Core.DTOs.CabinetDTO", "Cabinet")
                        .WithMany("Exams")
                        .HasForeignKey("IdCabinet");

                    b.Navigation("Cabinet");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.CabinetDTO", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.DepartmentDTO", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.HospitalDTO", b =>
                {
                    b.Navigation("Cabinets");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.NumberDTO", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.PatientDTO", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.UserDTO", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("XRayJournal.Core.DTOs.XRayExamDTO", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
